### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by tricksaberissexy** [NotAika/AikaTweaks#5]
The first one, bloom runs really weirdly. There's a bunch of popping and it isn't nice to play with.
The second one, crashing. I had my refresh rate and resolution at max, so that might have had something to do with it.
Other than that, great job Aika! It really feels like PCVR beat saber!

**Comment by uslashdeleted** [comment]
the first one is because you're running at 1.4 render resoultion and 120hz, bloom doesnt run that well.
i recommend running at 0.75 and 90hz for bloom
you can do 1.00 and 60hz for bloom and smoke in case you record content.

**Comment by BoogieHasFun** [comment]
please close this issue, because its pretty much a wontfix issue because oculus blocked you changing clock speeds on the quest 1 and 2
----------------------------------------
im pretty much saying it wont be fixed because of gpu and cpu is too slow for your settings (clock speeds and cooling is slowing it down), also meaning you cant fix it.
